/*
 * Public homepage content. Text may be a string or an object with zh/en keys.
 * Keep unconfirmed CV items out of these arrays; empty sections are hidden.
 */
window.SITE_CONTENT = {
  ui: {
    zh: {
      skip: "跳到正文",
      navLabel: "主导航",
      navAbout: "关于",
      navWork: "作品",
      navInterests: "兴趣",
      navEducation: "教育",
      navInternships: "实习",
      navPublications: "论文",
      navAwards: "获奖",
      navTeaching: "教学",
      navContact: "联系",
      heroEyebrow: "个人主页",
      heroGreeting: "你好，我是",
      heroScroll: "了解更多",
      aboutLabel: "关于",
      aboutHeading: "关于我",
      advisorLabel: "导师",
      workLabel: "作品",
      workHeading: "我的作品",
      workLink: "查看详情",
      interestsLabel: "兴趣",
      interestsHeading: "兴趣所在",
      educationLabel: "教育",
      educationHeading: "教育经历",
      internshipsLabel: "实习",
      internshipsHeading: "实习经历",
      publicationsLabel: "论文",
      publicationsHeading: "论文发表",
      awardsLabel: "获奖",
      awardsHeading: "获奖经历",
      teachingLabel: "教学",
      teachingHeading: "教学经历",
      recordLink: "查看详情",
      contactLabel: "联系",
      contactHeading: "联系",
      footerNote: "个人主页",
      languageLabel: "选择界面语言",
    },
    en: {
      skip: "Skip to content",
      navLabel: "Main navigation",
      navAbout: "About",
      navWork: "Work",
      navInterests: "Interests",
      navEducation: "Education",
      navInternships: "Internships",
      navPublications: "Publications",
      navAwards: "Awards",
      navTeaching: "Teaching",
      navContact: "Contact",
      heroEyebrow: "Personal homepage",
      heroGreeting: "Hello, I'm",
      heroScroll: "Get to know me",
      aboutLabel: "About",
      aboutHeading: "About",
      advisorLabel: "Advisor",
      workLabel: "Work",
      workHeading: "Selected work",
      workLink: "View details",
      interestsLabel: "Interests",
      interestsHeading: "Beyond work",
      educationLabel: "Education",
      educationHeading: "Education",
      internshipsLabel: "Internships",
      internshipsHeading: "Internships",
      publicationsLabel: "Publications",
      publicationsHeading: "Publications",
      awardsLabel: "Awards",
      awardsHeading: "Awards",
      teachingLabel: "Teaching",
      teachingHeading: "Teaching",
      recordLink: "View details",
      contactLabel: "Contact",
      contactHeading: "Contact",
      footerNote: "Personal homepage",
      languageLabel: "Choose display language",
    },
  },
  profile: {
    name: { zh: "徐皓天", en: "Haotian Xu" },
    intro: {
      zh: "北京大学计算机学院 2026 级博士生。",
      en: "PhD student at the School of Computer Science, Peking University, starting in 2026.",
    },
    about: {
      zh: "本科就读于北京大学图灵班，学习信息与计算科学。2026 年夏在 DeepSeek Harness 组实习，现为北京大学计算机学院博士生。",
      en: "I studied Information and Computer Science in the Turing Class at Peking University. After a summer internship with the DeepSeek Harness team in 2026, I am now a PhD student at Peking University.",
    },
    advisor: {
      name: { zh: "谢辽夏", en: "Sergey Mechtaev" },
      url: "https://mechtaev.com/",
    },
  },
  work: [],
  interests: [],
  records: {
    education: [
      {
        title: { zh: "北京大学", en: "Peking University" },
        subtitle: { zh: "计算机学院", en: "School of Computer Science" },
        description: {
          zh: "博士研究生 · 计算机科学与技术专业 · 编程语言与理论班",
          en: "PhD student in Computer Science and Technology · Programming Languages and Theory Class",
        },
        period: { zh: "2026–至今", en: "2026–Present" },
      },
      {
        title: { zh: "北京大学", en: "Peking University" },
        subtitle: {
          zh: "信息科学技术学院",
          en: "School of Electronics Engineering and Computer Science",
        },
        period: { zh: "2022.09–2026.06", en: "Sep 2022 – Jun 2026" },
        description: { zh: "本科 · 信息与计算科学专业 · 图灵班", en: "Undergraduate studies in Information and Computer Science · Turing Class" },
      },
    ],
    internships: [
      {
        title: { zh: "DeepSeek", en: "DeepSeek" },
        subtitle: { zh: "AGI 实习生 · Harness 组", en: "AGI Intern · Harness team" },
        period: { zh: "2026.07.06–2026.09.09", en: "Jul 6 – Sep 9, 2026" },
        url: "https://github.com/deepseek-ai/deepseek-harness",
        linkLabel: { zh: "DeepSeek Harness · 开源项目", en: "DeepSeek Harness · Open-source project" },
      },
    ],
    publications: [
      {
        title: "DeepSeek-V4.1-Flash: Pushing the Limits of KV Cache Compression",
        authors: ["DeepSeek-AI"],
        subtitle: { zh: "共同作者：Haotian Xu", en: "Co-author: Haotian Xu" },
        period: "2026",
        description: { zh: "技术报告", en: "Technical report" },
        links: [
          { label: { zh: "报告", en: "Report" }, url: "https://huggingface.co/deepseek-ai/DeepSeek-V4.1-Flash/blob/main/DeepSeek_V41_Tech_Report.pdf" },
        ],
      },
      {
        title: "Reducing Hallucinations in LLM-Generated Code via Semantic Triangulation",
        authors: ["Yihan Dai", "Sijie Liang", "Haotian Xu", "Peichu Xie", "Sergey Mechtaev"],
        highlightAuthor: "Haotian Xu",
        period: "OOPSLA 2026",
        description: { zh: "已录用", en: "Accepted" },
        links: [
          { label: { zh: "论文", en: "Paper" }, url: "https://arxiv.org/abs/2511.12288" },
          { label: { zh: "代码", en: "Code" }, url: "https://github.com/msv-lab/just-tri-it" },
        ],
      },
    ],
    awards: [
      {
        title: { zh: "John Hopcroft 奖学金", en: "John Hopcroft Scholarship" },
        subtitle: { zh: "北京大学", en: "Peking University" },
        period: { zh: "2024、2025", en: "2024, 2025" },
      },
      {
        title: { zh: "ICPC 亚洲区域赛昆明站", en: "ICPC Asia Kunming Regional Contest" },
        subtitle: { zh: "金牌（打星）", en: "Gold Medal (unofficial participation)" },
        period: { zh: "2024", en: "2024" },
      },
      {
        title: { zh: "北京大学程序设计竞赛", en: "Peking University Programming Contest" },
        subtitle: { zh: "二等奖", en: "Second Prize" },
        period: { zh: "2024", en: "2024" },
      },
      {
        title: { zh: "全国青少年信息学奥林匹克竞赛（NOI）", en: "NOI" },
        subtitle: { zh: "银牌", en: "Silver Medal" },
        period: { zh: "2020", en: "2020" },
      },
    ],
    teaching: [
      {
        title: { zh: "计算概论 A", en: "Introduction to Computation (A)" },
        subtitle: { zh: "北京大学 · 助教", en: "Peking University · Teaching Assistant" },
        period: { zh: "2025 秋季、2026 秋季（正在担任）", en: "Fall 2025, Fall 2026 (current)" },
        description: {
          zh: "2025 秋季主要负责期中与期末考试命题",
          en: "Primarily responsible for writing the midterm and final exams in Fall 2025",
        },
      },
      {
        title: { zh: "软件分析技术", en: "Software Analysis" },
        subtitle: { zh: "北京大学 · 助教", en: "Peking University · Teaching Assistant" },
        period: { zh: "2026 秋季 · 正在担任", en: "Fall 2026 · Current" },
        url: "https://xiongyingfei.github.io/SA_new/2026/",
        linkLabel: { zh: "2026 秋季课程主页", en: "Fall 2026 course website" },
      },
    ],
  },
  contacts: [
    { label: "Email: xht@stu.pku.edu.cn", url: "mailto:xht@stu.pku.edu.cn" },
    { label: { zh: "Github: pku-xht", en: "Github: pku-xht" }, url: "https://github.com/pku-xht" },
  ],
};
